2021-03-21 18:15:59,225 -  nornir.core -     INFO -        run() - Running task 'load_variable' with args {} on 6 hosts
2021-03-21 18:15:59,332 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'Configuring iBGP' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: send_config() got an unexpected keyword argument 'config_commands'

2021-03-21 18:15:59,343 - nornir.core.task -    ERROR -      start() - Host 'RR-1': task 'Configuring iBGP' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: send_config() got an unexpected keyword argument 'config_commands'

2021-03-21 18:15:59,344 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'load_variable' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 18, in load_variable
    int_ospf_bgp_configuration(task)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 28, in int_ospf_bgp_configuration
    task.run(task=send_config,
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring iBGP (failed)


2021-03-21 18:15:59,351 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'Configuring iBGP' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: send_config() got an unexpected keyword argument 'config_commands'

2021-03-21 18:15:59,351 - nornir.core.task -    ERROR -      start() - Host 'RR-1': task 'load_variable' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 18, in load_variable
    int_ospf_bgp_configuration(task)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 28, in int_ospf_bgp_configuration
    task.run(task=send_config,
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring iBGP (failed)


2021-03-21 18:15:59,351 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'Configuring iBGP' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: send_config() got an unexpected keyword argument 'config_commands'

2021-03-21 18:15:59,351 - nornir.core.task -    ERROR -      start() - Host 'RR-2': task 'Configuring iBGP' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: send_config() got an unexpected keyword argument 'config_commands'

2021-03-21 18:15:59,352 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'load_variable' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 18, in load_variable
    int_ospf_bgp_configuration(task)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 28, in int_ospf_bgp_configuration
    task.run(task=send_config,
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring iBGP (failed)


2021-03-21 18:15:59,362 - nornir.core.task -    ERROR -      start() - Host 'R4': task 'Configuring iBGP' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: send_config() got an unexpected keyword argument 'config_commands'

2021-03-21 18:15:59,362 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'load_variable' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 18, in load_variable
    int_ospf_bgp_configuration(task)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 28, in int_ospf_bgp_configuration
    task.run(task=send_config,
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring iBGP (failed)


2021-03-21 18:15:59,362 - nornir.core.task -    ERROR -      start() - Host 'RR-2': task 'load_variable' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 18, in load_variable
    int_ospf_bgp_configuration(task)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 28, in int_ospf_bgp_configuration
    task.run(task=send_config,
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring iBGP (failed)


2021-03-21 18:15:59,363 - nornir.core.task -    ERROR -      start() - Host 'R4': task 'load_variable' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 18, in load_variable
    int_ospf_bgp_configuration(task)
  File "/Users/vishalgajjar/Documents/GitHub/DEVNET-INT-IP-OSPF-iBGP/int_ospf_bgp_config.py", line 28, in int_ospf_bgp_configuration
    task.run(task=send_config,
  File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring iBGP (failed)


2021-03-21 18:15:59,377 -  nornir.core -     INFO -        run() - Running task 'show_status_ospf_bgp' with args {} on 6 hosts
2021-03-21 18:23:06,446 -  nornir.core -     INFO -        run() - Running task 'load_variable' with args {} on 6 hosts
2021-03-21 18:23:28,654 -  nornir.core -     INFO -        run() - Running task 'show_status_ospf_bgp' with args {} on 6 hosts
2021-03-21 18:25:37,954 -  nornir.core -     INFO -        run() - Running task 'load_variable' with args {} on 6 hosts
2021-03-21 18:26:01,206 -  nornir.core -     INFO -        run() - Running task 'show_status_ospf_bgp' with args {} on 6 hosts
2021-03-21 18:27:22,893 -  nornir.core -     INFO -        run() - Running task 'load_variable' with args {} on 6 hosts
2021-03-21 18:27:45,717 -  nornir.core -     INFO -        run() - Running task 'show_status_ospf_bgp' with args {} on 6 hosts
